"""
Django settings for pangeaserver project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
from decouple import config
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f#u!2h@39_$*5wwihn_sxkyy^nd7)1&rqk0ynrm$$9z_5@qt_z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG')

ALLOWED_HOSTS = [
    "*",
    '.vercel.app', '.now.sh',
    "localhost:8000",
    "192.168.1.10:8000",
    "192.168.1.9:8000",
    "192.168.1.8:8000",
    "192.168.1.7:8000",
    "192.168.1.6:8000",
    "192.168.1.5:8000",
    "192.168.1.4:8000",
    "192.168.1.3:8000",
    "192.168.1.2:8000",
    "192.168.1.1:8000",
    "192.168.1.10:8000",
    "192.168.1.0:8000",
]

CORS_ORIGIN_WHITELIST = (
  'http://localhost:8000',
  'http://localhost:3000',
  'http://localhost:3001',
)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #Rest Framework
    'rest_framework',
    #corsheaders
    'corsheaders',   
    "mainapp"
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pangeaserver.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pangeaserver.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db1.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# settings.py

# Set the email backend to SMTP
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# SMTP configuration
EMAIL_HOST = config('EMAIL_HOST')  # Replace with your SMTP server's hostname
EMAIL_PORT = config('EMAIL_PORT') # Replace with your SMTP server's port'
EMAIL_HOST_USER = config('EMAIL_HOST_USER')  # Replace with your email address
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')  # Replace with your email password
EMAIL_USE_TLS = config('EMAIL_USE_TLS')  # Use TLS encryption for secure communication with the SMTP server
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')  # Replace with your email address (optional)


PANGEA_API_KEY =  config('PANGEA_API_KEY') 
PANGEA_DOMAIN = config('PANGEA_DOMAIN') 
PANGEA_AUDIT_TOKEN = config('PANGEA_AUDIT_TOKEN') 

TWILIO_ACCOUNT_SID = config('TWILIO_ACCOUNT_SID') #os.getenv("TWILIO_ACCOUNT_SID")
TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN') #os.getenv("TWILIO_AUTH_TOKEN")



CASHFREE_APPID=config('CASHFREE_APPID')
CASHFREE_SECRET=config('CASHFREE_SECRET')
CASHFREE_PRODUCTION_URL=config('CASHFREE_PRODUCTION_URL')
CASHFREE_TEST_URL=config('CASHFREE_TEST_URL')

# TEST_CASHFREE_CLIENTID = config('TEST_CASHFREE_CLIENTID')
# TEST_CASHFREE_CLIENTSECRET = config('TEST_CASHFREE_CLIENTSECRET')

# MSG91_AUTH_KEY = config('MSG91_AUTH_KEY')
# MSG91_DLT_TE_ID = config("MSG91_DLT_TE_ID")


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

# STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import os 
STATICFILES_DIRS = os.path.join(BASE_DIR,'static')
STATIC_ROOT = os.path.join(BASE_DIR,'staticfiles' , 'static')