"""
Django settings for pangeaserver project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-f#u!2h@39_$*5wwihn_sxkyy^nd7)1&rqk0ynrm$$9z_5@qt_z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "*",
    "localhost:8000",
    "192.168.1.10:8000",
    "192.168.1.9:8000",
    "192.168.1.8:8000",
    "192.168.1.7:8000",
    "192.168.1.6:8000",
    "192.168.1.5:8000",
    "192.168.1.4:8000",
    "192.168.1.3:8000",
    "192.168.1.2:8000",
    "192.168.1.1:8000",
    "192.168.1.10:8000",
    "192.168.1.0:8000",
]

CORS_ORIGIN_WHITELIST = (
  'http://localhost:8000',
  'http://localhost:3000',
  'http://localhost:3001',
)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #Rest Framework
    'rest_framework',
    #corsheaders
    'corsheaders',   
    "mainapp"
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pangeaserver.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pangeaserver.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_L10N = True
USE_TZ = True

PANGEA_API_KEY =  "pts_3p74jnyg2efgzfnzfr7doni6fntjvblw"

PANGEA_DOMAIN = "aws.us.pangea.cloud" #os.getenv("PANGEA_DOMAIN")
PANGEA_AUDIT_TOKEN = "pts_ubignpagyjsy6c4w3ptlfhs642oso7hf" #os.getenv("PANGEA_AUDIT_TOKEN")

TWILIO_ACCOUNT_SID = "AC79dbe5c957b93c79a2dbfa42922a586b"
TWILIO_AUTH_TOKEN = "2b0ff55bfd3b24bd1bc97c388a4d7f92"



CASHFREE_APPID="10561330d5f13885191bd786ff316501"
CASHFREE_SECRET="c4ed3ae9a37ef89c4143b611168b8ea0d9e2d484"
CASHFREE_PRODUCTION_URL="https://api.cashfree.com/api/v2/cftoken/order"
CASHFREE_TEST_URL="https://test.cashfree.com/api/v2/cftoken/order"

TEST_CASHFREE_CLIENTID = "CF104868CH9NHCQ1KJHI5CH33TDG"
TEST_CASHFREE_CLIENTSECRET = "839513ae16b35803dc18e316074b7e5cf00005dd"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
