# Generated by Django 4.2 on 2023-05-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_usermodel_email_usermodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
