# Generated by Django 4.2 on 2023-05-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_usermodel_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddedCardsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(blank=True, max_length=40, null=True)),
                ('card_number', models.CharField(blank=True, max_length=20, null=True)),
                ('card_type', models.CharField(blank=True, default='debit', max_length=20, null=True)),
                ('card_expiry', models.CharField(blank=True, max_length=20, null=True)),
                ('card_cvv', models.CharField(blank=True, max_length=20, null=True)),
                ('card_holder_name', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, default='Axis', max_length=20, null=True)),
                ('total_balance', models.FloatField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_pid', models.CharField(blank=True, max_length=40, null=True)),
                ('to_pid', models.CharField(blank=True, max_length=40, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('card_id', models.CharField(blank=True, max_length=40, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=20, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=40, null=True)),
                ('transaction_status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='usermodel',
            name='card_added',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_pin_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='pin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
