# Generated by Django 4.2 on 2023-05-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_addedcardsmodel_transactionmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOTPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(blank=True, max_length=40, null=True)),
                ('otp', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='usermodel',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
