# Generated by Django 4.2 on 2023-05-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_notificationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='message',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='pid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
