# Generated by Django 4.2 on 2023-05-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_notificationmodel_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addedcardsmodel',
            name='bank_name',
            field=models.CharField(blank=True, default='Axis', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='addedcardsmodel',
            name='card_holder_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='card_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='from_pid',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='to_pid',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='transaction_status',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='pid',
            field=models.CharField(max_length=256, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='pin',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
